# Generated by Django 3.1 on 2021-02-27 18:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=60),
        ),
    ]
