# Generated by Django 3.1 on 2021-02-28 17:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210228_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=60),
        ),
    ]
