# Generated by Django 3.1 on 2021-02-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0005_comment_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='index_referenced_to',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='index_referenced_to_related_to_article',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
