# Generated by Django 3.1 on 2021-03-07 07:56

import django.contrib.postgres.fields.hstore
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0008_auto_20210228_2030'),
    ]

    operations = [
        HStoreExtension(),
        migrations.AddField(
            model_name='blogpost',
            name='params',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={'basic': 'false'}),
        ),
    ]
