# Generated by Django 3.1 on 2021-03-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0009_blogpost_params'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='params',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='basic',
            field=models.BooleanField(default=False),
        ),
    ]
