# Generated by Django 3.0.8 on 2020-08-01 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_auto_20200801_2336'),
        ('images', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
