# Generated by Django 3.1 on 2021-03-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_image_total_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDTO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='analyse/%Y/%m/%d/')),
            ],
        ),
    ]
