# Generated by Django 3.1 on 2021-03-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_imagedto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedto',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
